### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by fineless71** [js6pak/mojangfix#17]
I randomly got this crash, I don't know what I did:
```
java.lang.IndexOutOfBoundsException: Index: 43, Size: 39
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at net.minecraft.class_71.method_2078(class_71.java:124)
	at net.minecraft.class_504.method_1708(class_504.java:106)
	at net.minecraft.class_293.handler$zep000$mojangfix$onKeyPressed(class_293.java:609)
	at net.minecraft.class_293.method_117(class_293.java:184)
	at net.minecraft.class_32.method_132(class_32.java:134)
	at net.minecraft.class_32.method_130(class_32.java:112)
	at net.minecraft.client.Minecraft.method_2137(Minecraft.java:1299)
	at net.minecraft.client.Minecraft.run(Minecraft.java:754)
	at java.lang.Thread.run(Thread.java:750)
```

(I see mojang fix in the stack trace so I reported here, although I have other mods. LMK if this mod isn't the cause)

**Comment by telvarost** [comment]
> I randomly got this crash, I don't know what I did:
> 
> ```
> java.lang.IndexOutOfBoundsException: Index: 43, Size: 39
> 	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
> 	at java.util.ArrayList.get(ArrayList.java:435)
> 	at net.minecraft.class_71.method_2078(class_71.java:124)
> 	at net.minecraft.class_504.method_1708(class_504.java:106)
> 	at net.minecraft.class_293.handler$zep000$mojangfix$onKeyPressed(class_293.java:609)
> 	at net.minecraft.class_293.method_117(class_293.java:184)
> 	at net.minecraft.class_32.method_132(class_32.java:134)
> 	at net.minecraft.class_32.method_130(class_32.java:112)
> 	at net.minecraft.client.Minecraft.method_2137(Minecraft.java:1299)
> 	at net.minecraft.client.Minecraft.run(Minecraft.java:754)
> 	at java.lang.Thread.run(Thread.java:750)
> ```
> 
> (I see mojang fix in the stack trace so I reported here, although I have other mods. LMK if this mod isn't the cause)

It is caused by index out of bounds exception when trying to swap an item from a furnace to your hotbar.
There is now a PR pending to fix the issue 👍 
https://github.com/js6pak/mojangfix/pull/20
